"""Core scene graph types and registries."""

from .actions import ACTION_SPECS, ActionSpec, ActionType, action_spec
from .edges import EdgeCategory, EdgeType, SpatialRelation
from .floorplan_templates import (
    FLOORPLAN_LIBRARY,
    HOME_FLOORPLAN_TEMPLATES,
    FloorplanTemplate,
    get_floorplan_template,
    get_floorplan_template_registry,
    get_home_floorplan_template,
    list_floorplan_templates,
    list_home_floorplan_templates,
)
from .nodes import Agent, BaseNode, Floor, MobileTool, NodeType, Object, Room
from .npc_library import (
    DEFAULT_ROLE,
    HOME_NPC_LIBRARY,
    HOSPITAL_NPC_LIBRARY,
    ROLE_SCHEDULES,
    ScheduleEntry,
    get_default_npcs,
    planned_activity,
    schedule_for_role,
)
from .object_library import (
    OBJECT_LIBRARY,
    build_object_node,
    get_object_spec,
    get_object_template,
    get_objects_for_room,
    list_available_objects,
    list_object_types,
)
from .room_library import (
    FLOORPLAN_LIBRARY as ROOM_FLOORPLAN_LIBRARY,
    HOME_ROOM_TYPE_REGISTRY,
    ROOM_LIBRARY,
    FloorplanTemplate as RoomFloorplanTemplate,
    RoomTypeSpec,
    get_floorplan_template as get_room_floorplan_template,
    get_floorplan_template_registry,
    get_home_floorplan_template,
    get_room_spec,
    get_room_type_registry,
    get_room_type_spec,
    list_floorplan_templates,
    list_home_floorplan_templates,
    list_room_types,
)
from .scenegraph import SceneGraph

__all__ = [
    "ACTION_SPECS",
    "ActionSpec",
    "ActionType",
    "Agent",
    "DEFAULT_ROLE",
    "BaseNode",
    "EdgeCategory",
    "EdgeType",
    "FLOORPLAN_LIBRARY",
    "Floor",
    "FloorplanTemplate",
    "HOME_FLOORPLAN_TEMPLATES",
    "HOME_NPC_LIBRARY",
    "HOME_ROOM_TYPE_REGISTRY",
    "HOSPITAL_NPC_LIBRARY",
    "MobileTool",
    "NodeType",
    "OBJECT_LIBRARY",
    "Object",
    "ROOM_LIBRARY",
    "Room",
    "RoomTypeSpec",
    "ROLE_SCHEDULES",
    "SceneGraph",
    "ScheduleEntry",
    "SpatialRelation",
    "action_spec",
    "build_object_node",
    "get_default_npcs",
    "get_floorplan_template",
    "get_floorplan_template_registry",
    "get_home_floorplan_template",
    "get_object_spec",
    "get_object_template",
    "get_objects_for_room",
    "get_room_floorplan_template",
    "get_room_spec",
    "get_room_type_registry",
    "get_room_type_spec",
    "list_available_objects",
    "list_floorplan_templates",
    "list_home_floorplan_templates",
    "list_object_types",
    "list_room_types",
    "planned_activity",
    "schedule_for_role",
]
