"""Static core definitions for scene graph, actions, states, and rules."""

from .actions import ACTION_SPECS, ActionSpec, ActionType, action_spec
from .action_schemas import ACTION_SCHEMAS, ActionContext, ActionSchema, apply_action_schema, validate_action_schema
from .domain_rules import APPLIANCE_CYCLE_STEPS, DRYING_RACK_STEPS, DUMP_RULES, TRASHABLE_SEMANTICS
from .edges import EdgeCategory, EdgeType, SpatialRelation
from .nodes import (
    CONTROL_OBJECT_TYPES,
    ControlObject,
    FixedObject,
    Floor,
    Human,
    MovableObject,
    Node,
    NodeType,
    Robot,
    Room,
    node_type_from_legacy,
)
from .assets.npc_library import (
    DEFAULT_ROLE,
    HOME_NPC_LIBRARY,
    HOSPITAL_NPC_LIBRARY,
    NPC_EVENT_LIBRARY,
    ROLE_SCHEDULES,
    EventEffect,
    EventPrecondition,
    EventSpec,
    ScheduleEntry,
    get_default_npcs,
    get_event_spec,
    planned_activity,
    schedule_for_role,
)
from .assets.object_library import (
    Capability,
    OBJECT_LIBRARY,
    ObjectTemplate,
    build_object_node,
    get_object_spec,
    get_object_template,
    get_objects_for_room,
    list_available_objects,
    list_object_types,
)
from .scenegraph import SceneGraph
from .states import DISCRETE_STATE_SPACE, DiscreteState
from .timed_transitions import apply_timed_transitions

__all__ = [
    "ACTION_SPECS",
    "ACTION_SCHEMAS",
    "APPLIANCE_CYCLE_STEPS",
    "ActionContext",
    "ActionSchema",
    "ActionSpec",
    "ActionType",
    "CONTROL_OBJECT_TYPES",
    "Capability",
    "ControlObject",
    "DEFAULT_ROLE",
    "DISCRETE_STATE_SPACE",
    "DRYING_RACK_STEPS",
    "DiscreteState",
    "DUMP_RULES",
    "EdgeCategory",
    "EdgeType",
    "EventEffect",
    "EventPrecondition",
    "EventSpec",
    "FixedObject",
    "Floor",
    "HOME_NPC_LIBRARY",
    "HOSPITAL_NPC_LIBRARY",
    "Human",
    "MovableObject",
    "NPC_EVENT_LIBRARY",
    "Node",
    "NodeType",
    "OBJECT_LIBRARY",
    "ObjectTemplate",
    "ROLE_SCHEDULES",
    "SceneGraph",
    "ScheduleEntry",
    "SpatialRelation",
    "TRASHABLE_SEMANTICS",
    "action_spec",
    "apply_action_schema",
    "apply_timed_transitions",
    "build_object_node",
    "get_default_npcs",
    "get_event_spec",
    "get_object_spec",
    "get_object_template",
    "get_objects_for_room",
    "list_available_objects",
    "list_object_types",
    "node_type_from_legacy",
    "planned_activity",
    "schedule_for_role",
    "validate_action_schema",
]
