"""initial web platform schema

Revision ID: a7cf8f1665fc
Revises:
Create Date: 2026-05-22 00:16:01.924822
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

Text = sa.Text

revision = 'a7cf8f1665fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenes',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scene_versions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('scene_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('graph_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'version', name='uq_scene_versions_scene_version')
    )
    op.create_index(op.f('ix_scene_versions_scene_id'), 'scene_versions', ['scene_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('scene_version_id', sa.String(length=128), nullable=False),
    sa.Column('control_mode', sa.String(length=32), nullable=False),
    sa.Column('visibility_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scene_version_id'], ['scene_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_control_mode'), 'runs', ['control_mode'], unique=False)
    op.create_index(op.f('ix_runs_scene_version_id'), 'runs', ['scene_version_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_visibility_mode'), 'runs', ['visibility_mode'], unique=False)
    op.create_table('scene_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_version_id', sa.String(length=128), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('target_key', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=128), nullable=False),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scene_version_id'], ['scene_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_edges_relation'), 'scene_edges', ['relation'], unique=False)
    op.create_index(op.f('ix_scene_edges_scene_version_id'), 'scene_edges', ['scene_version_id'], unique=False)
    op.create_index(op.f('ix_scene_edges_source_key'), 'scene_edges', ['source_key'], unique=False)
    op.create_index(op.f('ix_scene_edges_target_key'), 'scene_edges', ['target_key'], unique=False)
    op.create_table('scene_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_version_id', sa.String(length=128), nullable=False),
    sa.Column('node_key', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('semantic_type', sa.String(length=128), nullable=False),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scene_version_id'], ['scene_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_version_id', 'node_key', name='uq_scene_nodes_version_key')
    )
    op.create_index(op.f('ix_scene_nodes_node_key'), 'scene_nodes', ['node_key'], unique=False)
    op.create_index(op.f('ix_scene_nodes_scene_version_id'), 'scene_nodes', ['scene_version_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('metric_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_metric_name'), 'metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metrics_run_id'), 'metrics', ['run_id'], unique=False)
    op.create_index(op.f('ix_metrics_step_index'), 'metrics', ['step_index'], unique=False)
    op.create_table('run_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('observation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('candidate_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('selected_action', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('action_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('world_state_before', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('world_state_after', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('events', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_index', name='uq_run_steps_run_step')
    )
    op.create_index(op.f('ix_run_steps_actor_type'), 'run_steps', ['actor_type'], unique=False)
    op.create_index(op.f('ix_run_steps_run_id'), 'run_steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_steps_step_index'), 'run_steps', ['step_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_steps_step_index'), table_name='run_steps')
    op.drop_index(op.f('ix_run_steps_run_id'), table_name='run_steps')
    op.drop_index(op.f('ix_run_steps_actor_type'), table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_index(op.f('ix_metrics_step_index'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_run_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_name'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_scene_nodes_scene_version_id'), table_name='scene_nodes')
    op.drop_index(op.f('ix_scene_nodes_node_key'), table_name='scene_nodes')
    op.drop_table('scene_nodes')
    op.drop_index(op.f('ix_scene_edges_target_key'), table_name='scene_edges')
    op.drop_index(op.f('ix_scene_edges_source_key'), table_name='scene_edges')
    op.drop_index(op.f('ix_scene_edges_scene_version_id'), table_name='scene_edges')
    op.drop_index(op.f('ix_scene_edges_relation'), table_name='scene_edges')
    op.drop_table('scene_edges')
    op.drop_index(op.f('ix_runs_visibility_mode'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_scene_version_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_control_mode'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_scene_versions_scene_id'), table_name='scene_versions')
    op.drop_table('scene_versions')
    op.drop_table('scenes')
    # ### end Alembic commands ###
